---
- name: Ejecutar script para backup
  shell: ./setup.sh -e "backup_dest= {{ destino_final }}" -b
  args:
    chdir: "{{ dscript_install }}"
  register: backupaap_output
  
- name: Mostrar salida del backup
  debug:
    var: backupaap_output.stdout_lines
